### ISSUE TITLE
Preserve multiple white-spaces from collapsing into one

### ISSUE THREAD

**Issue by nikitalpopov** [nikitalpopov/fit-text#1]
To save the day:

```css
span {
  white-space: no-wrap;
}
```
